#!/usr/bin/env bash
# This script displays Hi on 9th line, Best School every other line
COUNTER=1
while [ $COUNTER -le 10 ]; do
    echo Best School

    if [ $COUNTER -eq 9 ]
    then
	echo Hi
    fi
    let COUNTER+=1
done
